# Generated by Django 5.0.14 on 2026-07-12 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique asset barcode / tracking label code.', max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / Ready'), ('ALLOCATED', 'Allocated'), ('MAINTENANCE', 'In Maintenance'), ('DISPOSED', 'Disposed')], default='DRAFT', max_length=30)),
                ('health_score', models.IntegerField(default=100, help_text='Estimated health level from 0 to 100.')),
                ('location', models.CharField(blank=True, help_text='Physical placement site.', max_length=255, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='assets/qrcodes/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset_asset',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Category name (e.g., Laptops, Ergonomic Chairs).', max_length=150, unique=True)),
                ('code', models.CharField(help_text='Short unique identifier code (e.g., LAP, CHR).', max_length=50, unique=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual straight-line depreciation rate percentage (e.g., 20.00).', max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_category',
                'ordering': ['name'],
            },
        ),
    ]
