# Generated by Django 5.0.14 on 2026-07-12 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Audit plan name (e.g., Q3 Hardware Audit).', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
            ],
            options={
                'verbose_name': 'Audit Cycle',
                'verbose_name_plural': 'Audit Cycles',
                'db_table': 'audit_cycle',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Check'), ('VERIFIED', 'Verified Present'), ('MISPLACED', 'Misplaced / Missing'), ('DAMAGED', 'Damaged')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Verification',
                'verbose_name_plural': 'Audit Verifications',
                'db_table': 'audit_verification',
                'ordering': ['status', 'asset__code'],
            },
        ),
    ]
