import csv
from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from apps.authentication.permissions import IsAdmin, IsAssetManager
from apps.assets.models import Asset
from openpyxl import Workbook
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


class ExportReportView(APIView):
    permission_classes = [IsAuthenticated, IsAssetManager | IsAdmin]

    def get(self, request):
        export_format = request.query_params.get('format', 'csv').lower()
        module = request.query_params.get('module', 'assets').lower()

        if module != 'assets':
            return HttpResponse("Unsupported reporting module.", status=400)

        assets = Asset.objects.select_related('category', 'department').all()

        if export_format == 'csv':
            return self.export_csv(assets)
        elif export_format == 'excel':
            return self.export_excel(assets)
        elif export_format == 'pdf':
            return self.export_pdf(assets)
        
        return HttpResponse("Invalid reporting format requested.", status=400)

    def export_csv(self, assets):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="assets_report.csv"'

        writer = csv.writer(response)
        writer.writerow(['Code', 'Name', 'Category', 'Department', 'Status', 'Health Score', 'Cost'])

        for asset in assets:
            writer.writerow([
                asset.code,
                asset.name,
                asset.category.name if asset.category else '',
                asset.department.name if asset.department else '',
                asset.status,
                asset.health_score,
                asset.purchase_cost
            ])
        return response

    def export_excel(self, assets):
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename="assets_report.xlsx"'

        wb = Workbook()
        ws = wb.active
        ws.title = "Assets Directory"

        # Write Header
        ws.append(['Asset Code', 'Asset Name', 'Category', 'Department', 'Status', 'Health Score', 'Purchase Cost'])

        # Write data
        for asset in assets:
            ws.append([
                asset.code,
                asset.name,
                asset.category.name if asset.category else '',
                asset.department.name if asset.department else '',
                asset.status,
                asset.health_score,
                float(asset.purchase_cost)
            ])

        wb.save(response)
        return response

    def export_pdf(self, assets):
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="assets_report.pdf"'

        # Setup PDF document Canvas using ReportLab
        p = canvas.Canvas(response, pagesize=letter)
        width, height = letter
        
        p.setFont("Helvetica-Bold", 18)
        p.drawString(50, height - 50, "AssetFlow ERP - Assets Directory Report")
        
        p.setFont("Helvetica", 10)
        p.drawString(50, height - 70, f"Generated by administrator. Total Assets: {assets.count()}")
        
        p.setStrokeColorRGB(0.8, 0.8, 0.8)
        p.line(50, height - 80, width - 50, height - 80)

        # Drawing table headers
        y = height - 110
        p.setFont("Helvetica-Bold", 10)
        p.drawString(50, y, "Code")
        p.drawString(150, y, "Name")
        p.drawString(300, y, "Category")
        p.drawString(400, y, "Status")
        p.drawString(480, y, "Health")

        p.setFont("Helvetica", 9)
        for asset in assets[:20]:  # Limit output in demo to keep it on one page
            y -= 20
            p.drawString(50, y, asset.code)
            p.drawString(150, y, asset.name[:25])
            p.drawString(300, y, asset.category.name[:18] if asset.category else '')
            p.drawString(400, y, asset.status)
            p.drawString(480, y, f"{asset.health_score}%")

        p.showPage()
        p.save()
        return response
